# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provision "shell", inline: <<-SHELL
    Start-Process -FilePath C:/vagrant_data/java/jdk-9.0.1_windows-x64_bin.exe -ArgumentList "INSTALLCFG=c:/vagrant_data/java/jdk-9.0.1_windows-x64_bin.properties" -Wait
  SHELL

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.network :forwarded_port, host: 33389, guest: 3389, auto_correct: true
end
